$(function(){
    $('.ohituji').hover(
        function(){
            $('.ohituji').css('background-color','rgba(255,255,255,0.8)');
        },
        function(){
            $('.ohituji').css('background-color','rgba(255,255,255,0.3)')
        }
    )
    $('.ohituji').click(
        function(){
            window.location.href="seiza/ohituji.html";
        }
    )
    $('.oushi').hover(
        function(){
            $('.oushi').css('background-color','rgba(255,255,255,0.8)');
        },
        function(){
            $('.oushi').css('background-color','rgba(255,255,255,0.3)')
        }
    )
    $('.oushi').click(
        function(){
            window.location.href="seiza/oushi.html";
        }
    )
    $('.hutago').hover(
        function(){
            $('.hutago').css('background-color','rgba(255,255,255,0.8)');
        },
        function(){
            $('.hutago').css('background-color','rgba(255,255,255,0.3)')
        }
    )
    $('.hutago').click(
        function(){
            window.location.href="seiza/hutago.html";
        }
    )
    $('.kani').hover(
        function(){
            $('.kani').css('background-color','rgba(255,255,255,0.8)');
        },
        function(){
            $('.kani').css('background-color','rgba(255,255,255,0.3)')
        }
    )
    $('.kani').click(
        function(){
            window.location.href="seiza/kani.html";
        }
    )
    $('.shishi').hover(
        function(){
            $('.shishi').css('background-color','rgba(255,255,255,0.8)');
        },
        function(){
            $('.shishi').css('background-color','rgba(255,255,255,0.3)')
        }
    )
    $('.shishi').click(
        function(){
            window.location.href="seiza/shishi.html";
        }
    )
    $('.otome').hover(
        function(){
            $('.otome').css('background-color','rgba(255,255,255,0.8)');
        },
        function(){
            $('.otome').css('background-color','rgba(255,255,255,0.3)')
        }
    )
    $('.otome').click(
        function(){
            window.location.href="seiza/otome.html";
        }
    )
    $('.tennbinn').hover(
        function(){
            $('.tennbinn').css('background-color','rgba(255,255,255,0.8)');
        },
        function(){
            $('.tennbinn').css('background-color','rgba(255,255,255,0.3)')
        }
    )
    $('.tennbinn').click(
        function(){
            window.location.href="seiza/tennbinn.html";
        }
    )
    $('.sasori').hover(
        function(){
            $('.sasori').css('background-color','rgba(255,255,255,0.8)');
        },
        function(){
            $('.sasori').css('background-color','rgba(255,255,255,0.3)')
        }
    )
    $('.sasori').click(
        function(){
            window.location.href="seiza/sasori.html";
        }
    )
    $('.ite').hover(
        function(){
            $('.ite').css('background-color','rgba(255,255,255,0.8)');
        },
        function(){
            $('.ite').css('background-color','rgba(255,255,255,0.3)')
        }
    )
    $('.ite').click(
        function(){
            window.location.href="seiza/ite.html";
        }
    )
    $('.yagi').hover(
        function(){
            $('.yagi').css('background-color','rgba(255,255,255,0.8)');
        },
        function(){
            $('.yagi').css('background-color','rgba(255,255,255,0.3)')
        }
    )
    $('.yagi').click(
        function(){
            window.location.href="seiza/yagi.html";
        }
    )
    $('.mizugame').hover(
        function(){
            $('.mizugame').css('background-color','rgba(255,255,255,0.8)');
        },
        function(){
            $('.mizugame').css('background-color','rgba(255,255,255,0.3)')
        }
    )
    $('.mizugame').click(
        function(){
            window.location.href="seiza/mizugame.html";
        }
    )
    $('.uo').hover(
        function(){
            $('.uo').css('background-color','rgba(255,255,255,0.8)');
        },
        function(){
            $('.uo').css('background-color','rgba(255,255,255,0.3)')
        }
    )
    $('.uo').click(
        function(){
            window.location.href="seiza/uo.html";
        }
    )
});